[package]
name = "battery-script"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.34", features = ["derive"] }
starship-battery = "0.10.1"
sysinfo = "0.34.1"
